[initialisation]
field_to_keep = "Adj Close"
portfolio_column = "Portfolio"

[portfolio]
MSFT = 0.14285714285714285
AAPL = 0.14285714285714285
NVDA = 0.14285714285714285
GOOGL = 0.14285714285714285
GOOG = 0.14285714285714285
AMZN = 0.14285714285714285
META = 0.14285714285714285

[index]
GSPC= 1

[view_mode]
print = true
pandasgui = true

[view]
column_values = "Values"
return = "Portfolio return"
variance = "Portfolio variance"
std = "Standard deviation"
sharpe = "Sharpe Ratio"
sortino = "Sortino Ratio"
drawdown = 'Maximum Drawdown'
Var95 = "Var 95"
CVar95 = "CVar 95"